apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: ansibleee-role
  namespace: openstack
spec:
  # We can specify either
  # - playbook: which will run with default ansible-runner options
  # - tasks: which will run a list of tasks in files inside roles
  # - args: which allows specify the whole command that we want to execute
  roles:
    strategy: free
    become: true
    tasks:
      - name: Generic standalone playbook running tasks
        import_role:
          name: edpm_podman
          tasks_from: configure.yml
        tags:
          - edpm_podman
      - name: Generic standalone playbook running tasks
        import_role:
          name: edpm_container_manage
          tasks_from: shutdown.yml
  inventory: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.0.0.4
      vars:
        ansible_ssh_user: root
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
  extraMounts:
    - volumes:
      - name: sshkey
        secret:
          secretName: ssh-key-secret
          items:
          - key: ssh-privatekey
            path: ssh_key
      mounts:
      - name: sshkey
        mountPath: /runner/env/ssh_key
        subPath: ssh_key
