name: Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs*
      - api/v1beta1/**
      - docs/**
      - Gemfile
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # this fetches all branches. Needed because we need gh-pages branch for deploy to work
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1.160.0
        with:
          ruby-version: '3.2'

      - name: Install Asciidoc
        run: make docs-dependencies
      - name: Build docs
        run: make docs

      - name: Prepare gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git branch -D gh-pages &>/dev/null || true
          git checkout -b gh-pages 95fa4ca0ec7a38ee8dc0aabcd39cbfa98745d3d4

      - name: Commit asciidoc docs
        run: |
          mv docs_build/ansibleee/index-upstream.html index.html
          git add index.html
          git commit -m "Rendered docs"

      - name: Push rendered docs to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git push --force origin gh-pages
